# Generated by Django 4.2.4 on 2023-08-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='education',
            name='user_cv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='cv.usercv'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercv',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usercv',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='user_cv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_histories', to='cv.usercv'),
            preserve_default=False,
        ),
    ]
